import type { ModelSpec } from "./types.ts";

export const BASE_MODELS: ModelSpec[] = [
  {
    provider: "openai",
    model: "gpt-4.1",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
  },
  {
    provider: "openai",
    model: "gpt-4.1-mini",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
  },
  {
    provider: "openai",
    model: "gpt-5",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
    openAiReasoningEffort: "minimal",
  },
  {
    provider: "openai",
    model: "gpt-5.1",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
    openAiReasoningEffort: "none",
  },
  {
    provider: "openai",
    model: "gpt-5.2",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
    openAiReasoningEffort: "none",
  },
  {
    provider: "openai",
    model: "gpt-5.4",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
    openAiReasoningEffort: "none",
  },
  {
    provider: "openai",
    model: "gpt-5.5",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
    openAiReasoningEffort: "none",
  },
  {
    provider: "openai",
    model: "gpt-5-mini",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
    openAiReasoningEffort: "minimal",
  },
  {
    provider: "openai",
    model: "chat-latest",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default", "priority"],
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-5-20250929",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["standard_only", "auto"],
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-6",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["standard_only", "auto"],
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-5-20251101",
    include: true,
    supportsVariants: ["baseline", "low-effort"],
    tiers: ["standard_only", "auto"],
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-6",
    include: true,
    supportsVariants: ["baseline", "low-effort"],
    tiers: ["standard_only", "auto"],
  },
  {
    provider: "gemini",
    model: "gemini-2.5-pro",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default"],
  },
  {
    provider: "gemini",
    model: "gemini-2.5-flash",
    include: true,
    supportsVariants: ["baseline", "thinking-off"],
    tiers: ["default"],
  },
  {
    provider: "gemini",
    model: "gemini-2.5-flash-lite",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default"],
  },
  {
    provider: "gemini",
    model: "gemini-3-flash-preview",
    include: true,
    supportsVariants: ["baseline", "thinking-off"],
    tiers: ["default"],
  },
  {
    provider: "gemini",
    model: "gemini-3-pro-preview",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default"],
  },
  {
    provider: "gemini",
    model: "gemini-3.1-pro-preview",
    include: true,
    supportsVariants: ["baseline"],
    tiers: ["default"],
  },
  {
    provider: "gemini",
    model: "gemini-3.1-flash-lite-preview",
    include: true,
    supportsVariants: ["baseline", "thinking-off"],
    tiers: ["default"],
  },
];
